---
title: "analysisOfAZandON"
author: "Ji Won Chung"
date: "12/5/2017"
output: html_document
---

```{r}
library(tree)
library(dplyr)
library(ggplot2)
library(randomForest)


library(rpart.plot)
library(rpart)
```

```{r}
azDf = read.csv('arizonaDf.csv', header = TRUE) 
print(summary(azDf))
nObservations = nrow(azDf)
nFactors = ncol(azDf)
print(nObservations)
print(nFactors)
azDf <-subset(azDf, select = -c(state))
azDf <-subset(azDf, select = -c(X, level_0, index, Unnamed..0, business_id, city))
azDf <-subset(azDf, select = -c(neighborhood))
```


```{r}
ontarioDf = read.csv('onDf.csv', header = TRUE) 
print(summary(ontarioDf))
nObservations_ontario = nrow(ontarioDf)
nFactors_ontario = ncol(ontarioDf)
print(nObservations_ontario)
print(nFactors_ontario)
ontarioDf <-subset(ontarioDf, select = -c(state))
ontarioDf <-subset(ontarioDf, select = -c(X, level_0, index, Unnamed..0, business_id, city))
ontarioDf <-subset(ontarioDf, select = -c(neighborhood))
print(colnames(ontarioDf)) 
```
```{r}
set.seed(1)
```

```{r}
azDf$stars <- as.numeric(azDf$stars)
azDf$review_count <- as.numeric(azDf$review_count)

print(levels(azDf$Alcohol))
azDf$Alcohol<- factor(azDf$Alcohol, levels = c("Unknown", "none", "beer_and_wine", "full_bar"))
print(levels(azDf$Alcohol))

print(levels(azDf$NoiseLevel))
azDf$NoiseLevel<- factor(azDf$NoiseLevel, levels = c("Unknown", "quiet", "average", "very_loud"))
print(levels(azDf$NoiseLevel))

print(levels(azDf$RestaurantsAttire))
azDf$RestaurantsAttire<- factor(azDf$RestaurantsAttire, levels = c("Unknown", "casual", "dressy", "formal"))
print(levels(azDf$RestaurantsAttire))

print(levels(azDf$RestaurantsPriceRange2 )) 
azDf$RestaurantsPriceRange2<- factor(azDf$RestaurantsPriceRange2, levels = c("Unknown", "1.0", "2.0", "3.0", "4.0"))
print(levels(azDf$RestaurantsPriceRange2))

print(levels(azDf$WiFi )) 
azDf$WiFi<- factor(azDf$WiFi, levels = c("Unknown", "no", "paid", "free"))
print(levels(azDf$WiFi))
```

```{r}
azCleanDf <- subset(azDf, select = -c( MondayOpeningHours, TuesdayOpeningHours, WednesdayOpeningHours, ThursdayOpeningHours, FridayOpeningHours, SaturdayOpeningHours, SundayOpeningHours, MondayClosingHours, TuesdayClosingHours, WednesdayClosingHours, ThursdayClosingHours, FridayClosingHours, SaturdayClosingHours, SundayClosingHours))

print(colnames(azCleanDf))
```



Train & Test Data 
```{r}
subsetSamples = round(nObservations*0.7)
train = azCleanDf %>% sample_n(subsetSamples)

test = azCleanDf %>% 
  setdiff(train)
```


Decision tree for review_count using train dataset 
```{r}
azReviewCount <- rpart(review_count ~ . , data = train, method = "anova")

tree_azReviewCount = tree(review_count~., data = train)
print(summary(tree_azReviewCount))
rpart.plot(azReviewCount) 
```
 

Decision tree for stars using train dataset 
```{r}
azStars <- rpart(stars ~ . , data = train, method = "anova")

tree_azStars = tree(stars~., data = train)
print(summary(tree_azStars))
rpart.plot(azStars) 
```
Decision tree for businessOpen using train dataset 
```{r}


azOpen <- rpart(is_open ~ . , data = train, method = "class")

tree_azOpen = tree(is_open~., data = train)
print(summary(tree_azOpen))
rpart.plot(azOpen) 
```

 
